name: CICD

on: push

jobs:
  cicd:
      name: cicd
      runs-on: ubuntu-latest
      steps:
        - name: Check code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
            
        - name: Run Super-Linter
          uses: github/super-linter@v3.17.0
          env:
           DEFAULT_BRANCH: main
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip 
            pip install -r requirements.txt

        - name: Run unit tests
          run: |
           pip install pytest pytest-cov
           pytest test_calculator.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

        - name: Build and Push Docker Image
          uses: mr-smithers-exellent/docker-build-push@v4
          with:
            image: cicdmt001/cicd_v1.0
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
