name: CICD

on: push

jobs:
  cicd:
      name: cicd
      runs-on: ubuntu-latest
      steps:
        - name: Check code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.8

        - name: Install dependencies
          run: |
            python -version
            python -m pip install --upgrade pip

        - name: Run unit tests
          run: test_calculator.py
            pip install pytest pytest-cov
            pytest test_calculator.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

        - name: Run Super-Linter
          uses: github/super-linter@v3.17.0
          env:
           DEFAULT_BRANCH: main
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
