name: CICD

on: push

jobs:
  cicd:
      name: cicd
      runs-on: ubuntu-latest
      steps:
        - name: Check code
          uses: actions/checkout@v2

        - name: Run Super-Linter
          uses: github/super-linter@v3.17.0
          env:
           DEFAULT_BRANCH: main
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip

        - name: Run unit tests
          run: test_calculator.py
